---
openebs_operator_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-operator.yaml

openebs_operator: openebs-operator-ns-openebs.yaml

openebs_operator_alias: openebs-operator.yaml

openebs_storageclass: openebs-storageclasses.yaml

utils_path: openebs/e2e/ansible/playbooks/utils

openebs_storageclasses_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-storageclasses.yaml


openebs_storageclasses_alias: openebs-storageclasses.yaml

percona_mysql_plugin_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml


percona_links:
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_file: demo-percona-mysql-pvc.yaml

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - percona-diffns-claim
  - percona-diffns

test_name: deploy openebs and percona with its own namespace

deb_packages:
  - python-pip

test_pod_regex: maya*|openebs*|pvc*|percona*

test_log_path: setup/logs/openebs-percona-ownnamespace.log

test_artifacts:
   - demo-percona-mysql-pvc.yaml
   - openebs-operator-ns-openebs.yaml

namespace: percona-app
