---
test_name: test_nw_failure_rep

utils_path: openebs/e2e/ansible/playbooks/utils

percona_links:
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_files:
  - percona.yaml
  - sql-test.sh

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - test-nw-failure
  - test-nw

delay_interavals: 
  - 3000
  - 6000
  - 10000

namespace: nw-rep

pumba_file: https://raw.githubusercontent.com/openebs/elves/master/chaos/pumba/pumba_kube.yml 

test_pod_regex: maya*|openebs*|pvc*|percona*|pumba*

test_log_path: setup/logs/network_failure_test.log

