---
- name: Delete cassandra service pod
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: default
    app_yml: "{{ svc_yaml_alias }}"

- name: Delete cassandra statefulset pod
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: default
    app_yml: "{{ stateful_yaml_alias }}"

- name: Delete cassandra loadgen pod
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: default
    app_yml: "{{ loadgen_yaml_alias }}"

- name: Get cassandra pvcs
  shell: kubectl get pvc -o custom-columns=:metadata.name --no-headers | grep cassandra-data
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete cassandra pvcs
  shell: source {{ profile }}; kubectl delete pvc {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ result.stdout_lines }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Confirm cassandra pod has been deleted
  shell: source {{ profile }}; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'cassandra' not in result.stdout"
  delay: 120
  retries: 6
  changed_when: true

- name: Get cassandra deploy
  shell: source {{ profile }}; kubectl get deploy --no-headers | awk {'print $1'}
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete cassandra deploy
  shell: source {{ profile }}; kubectl delete deploy {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ result.stdout_lines }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

