---
- include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ volume_def }}"

- name: Confirm the iSCSI target has been deleted
  shell: source ~/.profile; kubectl get pvc -n {{ namespace }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' not in result.stdout"
  delay: 120
  retries: 6
  changed_when: true

- name: Delete namespace
  command: kubectl delete ns {{ namespace }}
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true




