---
test_name: volume_memcheck_test
volume_def: test-pvc.yaml
io_duration: 200s
block_size: [512k,1M]
py_file: test-mem.py
count_num: 10000
mount_point: /mnt/jiva
volume_claim: memleak-test
namespace: memleak-test
utils_path: openebs/e2e/ansible/playbooks/utils
test_pod_regex: maya*|openebs*|pvc*
test_log_path: setup/logs/memleak_test.log
